In [2]:
import numpy as np

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [7]:
a = np.array([34, 32, 12, 45, 43])
a

array([34, 32, 12, 45, 43])

In [8]:
a[2]

np.int64(12)

In [9]:
np.arange(4, 10, 2)

array([4, 6, 8])

In [ ]:
np.linspace(0, 10, 20) # 20 numbers from 0 to 10 with equal distance

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Multi-dementional Arrays

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[1][2]

np.int64(6)

In [23]:
a[2]

array([7, 8, 9])

In [24]:
# a[row, column]
a[:, 2]

array([3, 6, 9])

## Randomly Generated Arrays

In [27]:
np.random.seed(2) # seed the random number generator
np.random.rand(5, 4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149, 0.07964548]])

In [28]:
np.random.randn(5, 4)

array([[-0.74787095,  0.00902525, -0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905, -0.33882197, -0.23618403],
       [-0.63765501, -1.18761229, -1.42121723, -0.1534952 ],
       [-0.26905696,  2.23136679, -2.43476758,  0.1127265 ],
       [ 0.37044454,  1.35963386,  0.50185721, -0.8442137 ]])

In [ ]:
np.random.randint(1, 10, (5, 4)) # low, high, size

array([[4, 1, 1, 3],
       [9, 9, 3, 7],
       [6, 7, 7, 7],
       [4, 9, 3, 2],
       [5, 9, 2, 7]])

In [30]:
a = np.arange(1, 5)
a


array([1, 2, 3, 4])

In [32]:
a + 1

array([2, 3, 4, 5])

In [33]:
a >= 3

array([False, False,  True,  True])

In [44]:
a = np.random.randint(2, 10, (1, 5))
b = np.random.randint(2, 10, (1, 5))


print(a)
print(b)
print(a >= b)
print(a[a >= b])



[[4 9 5 2 8]]
[[2 4 7 6 6]]
[[ True  True False False  True]]
[4 9 8]


In [50]:
a = np.random.randint(2, 50, (100,))

print(a)
print("Sum:", a.sum())
print("Mean:", a.mean())
print("Max:", a.max())
print("Min:", a.min())


[43 42 24  8 38 15 47  4  4  5 32 12 25 21 18 16 36 30 19  7 20  4 34 13
  7 35 10 10 18 31 30 38 24 23 37  8 16 43 13 18 46 14 26 38 30 28 14 42
 33 26 26  8 23 42 17 22 35 35 14 20  9 43 24 42 28 11 40 49 41 41  5 13
 31 45 31 29 48 12 26 44 45 38 27 28 45 22 34  6 20 28 44 35 46  2 49 18
 42 35 14 44]
Sum: 2651
Mean: 26.51
Max: 49
Min: 2
