In [2]:
import numpy as np

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [6]:
a = np.array([34, 32, 12, 45, 43])
a

array([34, 32, 12, 45, 43])

In [7]:
a[2]

np.int64(12)

In [8]:
np.arange(4, 10, 2)

array([4, 6, 8])

In [9]:
np.linspace(0, 10, 20) # 20 numbers from 0 to 10 with equal distance

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Multi-dementional Arrays

In [10]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a[1][2]

np.int64(6)

In [13]:
a[2]

array([7, 8, 9])

In [14]:
# a[row, column]
a[:, 2]

array([3, 6, 9])

## Randomly Generated Arrays

In [15]:
np.random.seed(2) # seed the random number generator
np.random.rand(5, 4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149, 0.07964548]])

In [16]:
np.random.randn(5, 4)

array([[-0.74787095,  0.00902525, -0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905, -0.33882197, -0.23618403],
       [-0.63765501, -1.18761229, -1.42121723, -0.1534952 ],
       [-0.26905696,  2.23136679, -2.43476758,  0.1127265 ],
       [ 0.37044454,  1.35963386,  0.50185721, -0.8442137 ]])

In [17]:
np.random.randint(1, 10, (5, 4)) # low, high, size

array([[4, 1, 1, 3],
       [9, 9, 3, 7],
       [6, 7, 7, 7],
       [4, 9, 3, 2],
       [5, 9, 2, 7]])

In [18]:
a = np.arange(1, 5)
a


array([1, 2, 3, 4])

In [19]:
a + 1

array([2, 3, 4, 5])

In [20]:
a >= 3

array([False, False,  True,  True])

In [21]:
a = np.random.randint(2, 10, (1, 5))
b = np.random.randint(2, 10, (1, 5))


print(a)
print(b)
print(a >= b)
print(a[a >= b])



[[3 7 7 3 4]]
[[6 4 9 8 5]]
[[False  True False False False]]
[7]


In [22]:
a = np.random.randint(2, 50, (100,))

print(a)
print("Sum:", a.sum())
print("Mean:", a.mean())
print("Max:", a.max())
print("Min:", a.min())


[39 12 10 28 37 29 34 18 23 45 31 18 42  8 12 39 19 17 32 15 28 41 45 49
 22 24 38 29  2 42 30 38 13 48 11  9 20  3 17 29 48 34 41 42 46 48 11 45
 16 32 48 33 34 18 23 45 36 23 44 21 30 35 10 45 24 26 49 13  3 45  7  9
 18 43 30 17 19 39 33 36 18 44 38 24 21 33 19 47 10 39 11 23 38 41 42 41
 21 28 38 42]
Sum: 2883
Mean: 28.83
Max: 49
Min: 2


### Matrix Multiplication


In [24]:
def vector_vector_multiplication(u, v):
    
    assert u.shape[0] == v.shape[0]
    
    result = 0.0

    for i in range(u.shape[0]):
        result += u[i] * v[i]

    return result

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

print(vector_vector_multiplication(u, v))

# or we can use np.dot
print(np.dot(u, v))

32.0
32


In [25]:
def matrix_vector_multiplication(U, v):
    
    assert U.shape[1] == v.shape[0]
    
    result = np.zeros(U.shape[0])

    for i in range(U.shape[0]):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

U = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

v = np.array([1, 2, 3])

print(matrix_vector_multiplication(U, v))

# or we can use np.dot
print(np.dot(U, v))

[14. 32. 50.]
[14 32 50]


In [27]:
def matrix_matrix_multiplication(U, V):
    
    assert U.shape[1] == V.shape[0]
    
    n = U.shape[0]
    m = V.shape[1]
    
    result = np.zeros((n, m))

    for i in range(n):
        for j in range(m):
            result[i, j] = vector_vector_multiplication(U[i], V[:, j])

    return result


U = np.array([
    [1, 2, 3],  
    [4, 5, 6],
    [7, 8, 9]
])

V = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix_matrix_multiplication(U, V))

# or we can use np.dot
print(np.dot(U, V))

[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
